name: Trusted Signing of payload.json via SignPath

on:
  workflow_dispatch:

jobs:
  sign-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Wichtig für Commit- & Branch-Verfolgung

      - name: Verify payload.json exists
        run: |
          if [ ! -f "payload.json" ]; then
            echo "payload.json nicht gefunden!"
            exit 1
          fi
          cat payload.json

      - name: Upload payload.json to GitHub as artifact
        id: upload-payload
        uses: actions/upload-artifact@v4
        with:
          name: payload-json
          path: payload.json

      - name: Submit signing request to SignPath
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: 'd3694686-eb3d-4e3d-aeb0-e9fff9e397a9'              # z. B. d3694686-eb3d-4e3d-aeb0-e9fff9e397a9
          project-slug: 'Liebherr_PoC_HashSigning'            # z. B. my-project
          signing-policy-slug: 'PoC_Signing_Liebherr'      # z. B. fast-signing
          github-artifact-id: ${{ steps.upload-payload.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: signed-output

      - name: Zeige signiertes Ergebnis
        run: |
          echo "Signiertes Artefakt:"
          ls -lh signed-output

      - name: Lade signiertes Artefakt hoch (optional)
        uses: actions/upload-artifact@v4
        with:
          name: signed-payload
          path: signed-output
