name: Trusted Signing of dummy.exe via SignPath

on:
  workflow_dispatch:

jobs:
  sign-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Wichtig für Commit- & Branch-Verfolgung

      - name: Verify dummy.exe exists
        run: |
          if [ ! -f "dummy.exe" ]; then
            echo "dummy.exe nicht gefunden!"
            exit 1
          fi
          cat dummy.exe

      - name: Upload dummy.exe to GitHub as artifact
        id: upload-payload
        uses: actions/upload-artifact@v4
        with:
          name: dummy.exe
          path: dummy.exe

      - id: optional_step_id
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: 'd3694686-eb3d-4e3d-aeb0-e9fff9e397a9'              
          project-slug: 'PoC_HashSigning'            
          signing-policy-slug: 'PoC_Signing'      
          github-artifact-id: ${{ steps.upload-payload.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: signed-output

      - name: Show signed-output contents
        run: ls -lh signed-output

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-output
          path: signed-output
